Kan 2 walka kazdy z kazdym
sgfn/rikishi pull request #11
Opened 2024-05-14 11:30 UTC by adam147g

Stworzyłem klasę AllVsAll która obsługuje system walk - każdy z każdym. Klasa implementuje stworzony przez @c-i-a-s-t-e-k interface MatchingSystem. W MatchingSystemTest dodałem sprawdzenie działania kodu.

2024-05-14 11:57 UTC, c-i-a-s-t-e-k reviewed
Co dokładniej zawiera lista trójwymiarowa results?

2024-05-14 12:53 UTC, adam147g commented
results zawiera obecny wynik danego meczu.
Przykładowo jeśli w meczu gra zawodnik o id 3 z id 4, a ich obecny wynik to 1:0, to w results[3][4][0] = results[4][3][1] = 1, results[3][4][1] = results[4][3][0] = 0

2024-05-14 14:09 UTC, Endrewzz requested changes
Could you add dogrywka, when two players have exact points score. Pls. 🥲

2024-05-21 11:38 UTC, c-i-a-s-t-e-k approved these changes
Dobra robota

Miej na uwadze że zmieniła się struktura projektu, ścieżka do paczki teraz to:
'''
backend/src/main/java/com/rikishi/backend/matching/systems
'''

2024-05-26 18:26 UTC, Kappaprideer approved these changes

2024-05-31 21:09 UTC, merged